// ─────────────────────────────────────────────────────────────
// HASAR ANALİZİ ATLASI — Case Data
// 25 production defect cases (wire rod + flat product)
// Images extracted from DOCX: /public/atlas/imageN.jpeg|png
// ─────────────────────────────────────────────────────────────

export const CATEGORIES = {
  wire: {
    id: "wire",
    tr: "Uzun Mamul Kusurlari",
    en: "Wire Rod Defects",
    color: "#2563eb",
    bg: "#1e3a6e",
    badge: "KANGAL / WIRE ROD",
  },
  flat: {
    id: "flat",
    tr: "Yassi Mamul Kusurlari",
    en: "Flat Product Defects",
    color: "#dc2626",
    bg: "#5c1a1a",
    badge: "BOBIN / COIL",
  },
};

export const CASES = [
  // ─── UZUN MAMUL — WIRE ROD ────────────────────────────────
  {
    no: 1,
    slug: "tel-yuzeyinde-cukur-bosluklari",
    category: "wire",
    tr: "Tel Yüzeyinde Çukur ve Boşluklar",
    en: "Pits and Voids on the Wire Surface",
    tags: ["yüzey", "çukur", "boşluk", "iç oksidasyon", "sürekli döküm", "kangal"],
    images: ["image3.jpeg","image4.jpeg","image5.jpeg","image6.JPG","image7.jpeg","image8.jpeg"],
    imgLabels: ["Makro görünüm","Yüzey deformasyonu","Optik mikroskop x100","Optik mikroskop x200","Kesit detayı","SEM görüntüsü"],
    imgLabels_en: ["Macroscopic view","Surface deformation","Optical microscopy x100","Optical microscopy x200","Cross-section detail","SEM image"],
    sikayet: "Yüzey Kusuru",
    sikayet_en: "Surface Defect",
    tespitler: [
      "Makro incelemelerde tel yüzeylerinde çukur, çatlak ve batık tipi kusurlar gözlenmiştir.",
      "Mikro incelemelerde yüzeyden kesit içerisine bakıldığında iç oksitlenme ile sarılmış çatlak tipinde tel içerisine ilerleyen kusur görülebilmektedir.",
      "SEM-EDS incelemelerinde oksit kalıntılar, kusurun sürekli döküm aşamasında kütük yüzeyinde oluşmuş kusurların varlığı ile geliştiğini göstermektedir.",
      "Kök neden analizi için kusurun başlangıç ve bitiş noktalarında mikro yapı incelemesi gereklidir.",
    ],
    tespitler_en: [
      "Macroscopic examination reveals pits, cracks, and subsurface defects on wire surfaces.",
      "Optical microscopy shows internal oxidation-wrapped cracks progressing from surface into the wire cross-section.",
      "SEM-EDS analysis confirms oxide residues developed from surface defects formed at the ingot surface during continuous casting.",
      "Root cause analysis requires microstructural examination at the defect initiation and termination points.",
    ],
    nedenler: [
      "Birinci kaynak: kangal üretimi sırasında oluşmuş yüzey kusurları — haddeleme sırasında kapanmamış yüzeye yapışmış oksit tabakaları ve yüzeye yakın uzamış inklüzyon hatları, tel çekme sırasında açılarak ilerleyen çatlaklara neden olabilir.",
      "İkinci kaynak: müşteri tel çekme prosesi — yetersiz yüzey hazırlığı, yüksek redüksiyon oranları, kalıp yüzey pürüzlülüğü veya soğutma–yağlama yetersizliği sürtünme gerilmelerini artırır.",
    ],
    nedenler_en: [
      "Primary source: wire rod surface defects formed during production — oxide layers adhering to unclosed surfaces during rolling and elongated inclusion lines near the surface can initiate progressive cracks during wire drawing.",
      "Secondary source: customer wire drawing process — insufficient surface preparation, high reduction ratios, die surface roughness, or inadequate cooling and lubrication increase frictional stresses.",
    ],
    onleme: [
      "Sürekli dökümde menisküs seviye ve osilasyon kontrolü; kalıpta taşma ve kanamaların önlenmesi",
      "Kalıp (mold flux) yönetimi: uygun viskozite–besleme hızı",
      "Tundish/refrakter temizliği ve yeniden oksidasyonun önlenmesi; Al(sol)–Ca ve toplam O hedeflerinin kontrolü",
    ],
    onleme_en: [
      "Control meniscus level and oscillation marks in continuous casting; prevent overflow and leakage in the mold",
      "Mold flux management: maintain appropriate viscosity and feeding rate",
      "Tundish and refractory cleaning; prevent reoxidation through Al(sol)–Ca and total O target control",
    ],
    kaynak: "ASM Handbook, Vol. 1 — Properties and Selection: Irons, Steels, and High-Performance Alloys; Vol. 15 — Casting",
  },
  {
    no: 2,
    slug: "tel-yuzeyinde-deformasyon-izleri",
    category: "wire",
    tr: "Tel Yüzeyinde Deformasyon İzleri, Boşluklar",
    en: "Deformation Marks and Cracks on Wire Surface",
    tags: ["deformasyon", "yüzey", "çatlak", "lap", "katmer", "tel çekme"],
    images: ["image9.png","image10.png","image11.jpeg","image12.png","image13.jpeg","image14.jpeg"],
    imgLabels: ["Makro görünüm","Yüzey deformasyonu","Optik mikroskop x100","Optik mikroskop x200","Kesit detayı","Çatlak ilerlemesi"],
    imgLabels_en: ["Macroscopic view","Surface deformation","Optical microscopy x100","Optical microscopy x200","Cross-section detail","Crack propagation"],
    sikayet: "Tel çekmede kopma veya kırılma / Yay imalatında kopma veya kırılma",
    sikayet_en: "Wire drawing breakage / Spring manufacturing breakage",
    tespitler: [
      "Makro incelemelerde tel yüzeylerinde batık, yığıntı ve çapak tipi yüzey kusurları gözlenmiştir.",
      "Mikro incelemelerde çatlaklar yüzeyden başlayarak içe doğru ilerlemekte, hadde yönünde uzamakta ve tel çekme deformasyonu ile büyümektedir.",
      "Yüzeyden başlayan kusurların içe doğru uzaması haddeleme sırasında oluşmuş yüzey hataları (katmer, dikiş, lap) ile ilişkilidir.",
    ],
    tespitler_en: [
      "Macroscopic examination reveals subsurface, ridge, and scale-type surface defects on wire surfaces.",
      "Optical microscopy shows cracks initiating from the surface and progressing inward, elongated along the rolling direction, and growing due to wire drawing deformation.",
      "Internal propagation of surface-initiated defects correlates with rolling-induced surface folds (laps, seams, and seams).",
    ],
    nedenler: [
      "Haddeleme sırasında kapanmamış oksit tabakaları ve yüzeye yakın inklüzyon hatları, tel çekme sırasında açılarak ilerleyen çatlaklara yol açar.",
      "Yetersiz yüzey hazırlığı (fosfatlama/kaplama eksikliği), yüksek redüksiyon oranları, kalıp pürüzlülüğü veya yağlama yetersizliği sürtünme gerilmelerini artırır.",
      "Söz konusu kusurların tamamen kangal kaynaklı olması kadar müşteri tel çekme prosesi koşullarının da şiddetlenmesinde rol oynadığı değerlendirilmelidir.",
    ],
    nedenler_en: [
      "Unclosed oxide layers and near-surface inclusion lines formed during rolling open and propagate as cracks during wire drawing.",
      "Insufficient surface preparation (lack of phosphating/coating), high reduction ratios, die surface roughness, or inadequate lubrication increase frictional stresses.",
      "Both the wire rod defects and the severity of customer wire drawing process conditions must be evaluated in tandem.",
    ],
    onleme: [
      "Kangal yüzey kalitesinin iyileştirilmesi; kütük yüzey muayenesi",
      "Tel çekme prosesinde kalıp geometrisi, yüzey hazırlığı ve yağlama kontrolü",
      "Redüksiyon oranlarının optimize edilmesi",
    ],
    onleme_en: [
      "Improve wire rod surface quality through ingot surface inspection",
      "Optimize die geometry, surface preparation, and lubrication control in wire drawing",
      "Optimize reduction ratios",
    ],
    kaynak: "ASM Handbook, Volume 14: Forming and Forging",
  },
  {
    no: 3,
    slug: "kangal-yuzeyinde-deformasyon-catlak",
    category: "wire",
    tr: "Kangal Yüzeyinde Deformasyon İzleri, Çatlak",
    en: "Deformation and Cracks on Wire Rod Surface",
    tags: ["kangal", "yüzey çatlak", "osilasyon", "mold flux", "kütük", "iç oksidasyon"],
    images: ["image15.jpeg","image16.jpeg","image17.jpeg"],
    imgLabels: ["Yüzey makro görünüm","Optik mikroskop x100","Optik mikroskop x200"],
    imgLabels_en: ["Surface macroscopic view","Optical microscopy x100","Optical microscopy x200"],
    sikayet: "Tel çekmede kopma veya kırılma / Yay imalatında kopma veya kırılma",
    sikayet_en: "Wire drawing breakage / Spring manufacturing breakage",
    tespitler: [
      "1006 kangal üzerinde yapılan incelemede yüzeyde uzunlamasına çizgi ve çatlak benzeri hatalar gözlenmiştir.",
      "Optik mikroskop görüntülerinde kusurların yüzeyden başlayarak çekme yönünde yüzey altına doğru ilerlediği tespit edilmiştir.",
      "Çatlak çevresinde oksit kalıntıları ve uzamış inklüzyon hatları görülmektedir.",
    ],
    tespitler_en: [
      "Examination of 1006 wire rod reveals longitudinal streaks and crack-like marks on the surface.",
      "Optical microscopy confirms defects initiating from the surface and progressing subsurface in the drawing direction.",
      "Oxide residues and elongated inclusion lines are observed around cracks.",
    ],
    nedenler: [
      "Kusurun kökeni büyük ölçüde kütük yüzeyindedir. Sürekli döküm sırasında kütük yüzeyine yapışıp tam temizlenmeyen döküm tozu/cüruf tabakası veya osilasyon izleri reheating fırınında iç oksidasyon bandı geliştirir.",
      "Yüksek basınçlı descaling'in yetersiz kaldığı bölgelerde oksit parçaları yüzeye gömülür; sıcak hadde pasolarında oksit dolgulu boyuna çatlak hâline gelir.",
      "Tel çekme sırasında uygulanan redüksiyon ve sürtünme gerilmeleri süreksizliği dallanmış çatlak olarak büyütür.",
    ],
    nedenler_en: [
      "The defect originates primarily at the ingot surface. During continuous casting, casting powder/slag layers adhering and incompletely cleaned from the ingot surface, or oscillation marks develop into internal oxidation bands in the reheating furnace.",
      "In regions where high-pressure descaling is insufficient, oxide fragments embed into the surface; during hot rolling passes, these form longitudinal cracks filled with oxides.",
      "Reduction and frictional stresses applied during wire drawing magnify the discontinuity into branched cracks.",
    ],
    onleme: [
      "Sürekli dökümde menisküs seviye ve osilasyon kontrolü; taşma ve kanamaların önlenmesi",
      "Kalıp (mold flux) yönetimi: uygun viskozite–besleme hızı",
      "Tundish/refrakter temizliği ve Al(sol)–Ca hedeflerinin kontrolü",
    ],
    onleme_en: [
      "Control meniscus level and oscillation marks in continuous casting; prevent overflow and leakage",
      "Mold flux management: maintain appropriate viscosity and feeding rate",
      "Tundish and refractory cleaning with Al(sol)–Ca target control",
    ],
    kaynak: "ASM Handbook, Vol. 1 — Properties and Selection; Vol. 15 — Casting",
  },
  {
    no: 4,
    slug: "white-layer-martensite-1",
    category: "wire",
    tr: "Deformasyon Sonucu Yüzeyde Sert Faz — Beyaz Tabaka Martenzit 1",
    en: "Hard Phase Formation (White Layer Martensite) — Case 1",
    tags: ["white layer", "martenzit", "sert faz", "tel çekme", "yüksek karbon", "1075", "1085"],
    images: ["image18.jpeg","image19.jpeg","image20.jpeg","image21.jpeg","image22.jpeg","image23.jpeg"],
    imgLabels: ["Kırılma makro görünüm","Nehir çizgileri","Sürtünme izleri","Optik mikroskop x100","Beyaz tabaka x500","Kenar detayı"],
    imgLabels_en: ["Fracture macroscopic view","River marks","Friction marks","Optical microscopy x100","White layer x500","Edge detail"],
    sikayet: "Tel çekmede kopma veya kırılma / Yay imalatında kopma veya kırılma",
    sikayet_en: "Wire drawing breakage / Spring manufacturing breakage",
    tespitler: [
      "Yüksek karbonlu kalın kangal çaplarında görülen bu kusurda kırılma yüzeylerinde nehir çizgileri (river marks) kırılmanın başladığı bölgeyi işaret eder.",
      "Kırılmanın başladığı noktada bir deformasyon izi ve sürtünme bölgelerinde aşırı ısınma-soğumaya bağlı sert yapılar oluşmuştur.",
      "White layer martenzit fazı mikroskop altında ince beyaz bir tabaka olarak gözlenir; ultra ince taneli formdadır.",
    ],
    tespitler_en: [
      "River marks on fracture surfaces of high-carbon thick wire rod indicate the region where fracture initiated.",
      "A deformation mark at fracture initiation and hard structures formed in friction zones due to localized heating and rapid cooling are observed.",
      "White layer martensite phase appears as a thin white band under microscopy in ultra-fine-grained form.",
    ],
    nedenler: [
      "White layer martenzit, tel çekme gibi yoğun deformasyon içeren işlemler sırasında yüksek karbonlu çeliklerin (%C ≥ 0.65) yüzeyinde oluşan çok sert ve kırılgan bir fazdır.",
      "Yüzeyde lokal 900–950 °C'ye ulaşan anlık ısınma ve ardından hızlı soğuma ile östenitten martenzite difüzyonsuz faz dönüşümü (BCT yapı) gerçekleşir.",
      "Lokal sıcaklık artışı; yüksek çekme hızları, tel-kalıp arasındaki sürtünme ve yetersiz yağlama koşullarında ortaya çıkar.",
    ],
    nedenler_en: [
      "White layer martensite is a very hard and brittle phase formed on the surface of high-carbon steels (%C ≥ 0.65) during severe deformation processes like wire drawing.",
      "Localized heating reaching 900–950 °C followed by rapid cooling causes diffusionless phase transformation from austenite to martensite (BCT structure).",
      "Local temperature increase occurs under high drawing speeds, friction between wire and die, and inadequate lubrication.",
    ],
    onleme: [
      "Tel çekme hızının kademeli artırılması ve kontrolü",
      "Yeterli ve uygun viskoziteli yağlama kullanımı",
      "Kalıp açılarının uygun tasarlanması ve yüzey kalitesinin artırılması",
      "Telin homojen mikroyapıda olması (Stelmor parametrelerinin optimizasyonu)",
    ],
    onleme_en: [
      "Control and gradually increase wire drawing speed",
      "Use adequate and properly viscous lubrication",
      "Properly design die angles and improve surface quality",
      "Ensure homogeneous microstructure in wire through Stelmor parameter optimization",
    ],
    kaynak: "Sipos K., López M., Trucco M. — Surface martensite white layer produced by adhesive sliding wear-friction in AISI 1065 steel",
  },
  {
    no: 5,
    slug: "white-layer-martensite-2",
    category: "wire",
    tr: "Deformasyon Sonucu Yüzeyde Sert Faz — Beyaz Tabaka Martenzit 2",
    en: "Hard Phase Formation (White Layer Martensite) — Case 2",
    tags: ["white layer", "martenzit", "sert faz", "heterojen sertlik", "tel çekme"],
    images: ["image24.png","image25.jpeg","image26.jpeg"],
    imgLabels: ["Yüzey renk farklılığı","Optik mikroskop x200","Beyaz tabaka detayı"],
    imgLabels_en: ["Surface color variation","Optical microscopy x200","White layer detail"],
    sikayet: "Tel çekmede kopma veya kırılma / Yay imalatında kopma veya kırılma",
    sikayet_en: "Wire drawing breakage / Spring manufacturing breakage",
    tespitler: [
      "Makro boyutta kangal yüzeyinde renk farklılıkları olarak görülen sürtünme izleri ve deformasyona uğramış kangal yüzeyi görünümü tespit edilebilmektedir.",
      "Yüzeyin sürtünme koşullarına bağlı olarak kangal veya tel yüzeyinde sert bir alan oluşmaktadır.",
      "Deformasyon şiddetine bağlı olarak sertlik değeri ve boyutu değişebilmektedir — heterojen sertlik dağılımı.",
    ],
    tespitler_en: [
      "Friction marks visible at macroscopic scale as color variations on wire rod surface and a deformed surface appearance are observed.",
      "Depending on friction conditions, a hard zone forms on the wire rod or wire surface.",
      "Hardness values and size vary depending on deformation intensity — heterogeneous hardness distribution.",
    ],
    nedenler: [
      "White layer martenzit mekanizması Case 1 ile aynıdır: %C ≥ 0.65 çelikte yüksek sürtünme → lokal 900–950 °C → hızlı soğuma → BCT yapı.",
      "Bu vakada deformasyon şiddeti farklılık gösterdiğinden sertlik değerleri daha değişken ve heterojen bir dağılım sergilemektedir.",
    ],
    nedenler_en: [
      "White layer martensite mechanism is identical to Case 1: high friction in %C ≥ 0.65 steel → local 900–950 °C → rapid cooling → BCT structure.",
      "In this case, because deformation intensity varies, hardness values display more variable and heterogeneous distribution.",
    ],
    onleme: [
      "Tel çekme hızının kademeli artırılması ve kontrolü",
      "Yeterli ve uygun viskoziteli yağlama kullanımı",
      "Kalıp açılarının uygun tasarlanması",
      "Telin homojen mikroyapıda olması",
    ],
    onleme_en: [
      "Control and gradually increase wire drawing speed",
      "Use adequate and properly viscous lubrication",
      "Properly design die angles",
      "Ensure homogeneous microstructure in wire",
    ],
    kaynak: "Sipos K., López M., Trucco M. — Surface martensite white layer in AISI 1065 steel",
  },
  {
    no: 6,
    slug: "tane-siniri-sementit-gbc",
    category: "wire",
    tr: "Tane Sınırı Sementit (GBC)",
    en: "Grain Boundary Cementite (GBC)",
    tags: ["GBC", "sementit", "tane sınırı", "hiperötektoid", "perlit", "Acm", "A1"],
    images: ["image27.png","image28.jpeg","image29.png","image30.jpeg","image31.jpeg","image32.jpeg","image33.jpeg","image34.jpeg","image35.jpeg","image36.jpeg"],
    imgLabels: ["GBC ağ yapısı x100","Tane sınırı detayı","Optik mikroskop x200","Merkez bölge","GBC network","Karbon zenginliği","SEM görüntüsü","Kırılma bölgesi","GBC oluşumu","Önlem karşılaştırma"],
    imgLabels_en: ["GBC network structure x100","Grain boundary detail","Optical microscopy x200","Center region","GBC network","Carbon enrichment","SEM image","Fracture region","GBC formation","Prevention comparison"],
    sikayet: "Tel çekmede kopma veya kırılma / Yay imalatında kopma veya kırılma",
    sikayet_en: "Wire drawing breakage / Spring manufacturing breakage",
    tespitler: [
      "Kırılma yaşanan kangal veya tel gözle tespit edilemez; kesitte yapılan mikroskop incelemelerinde beyaz renkte bir ağ (network) katmanı şeklinde kendini belli eder.",
      "Genellikle kesitin merkez bölgesinde daha yoğun gözlenmektedir.",
      "SEM incelemesinde beyaz hatlar boyunca karbon değeri artışı görülmektedir.",
    ],
    tespitler_en: [
      "Fractured wire rod cannot be detected by eye; cross-sectional microscopy reveals itself as a white network-like layer.",
      "Generally observed more intensely in the center region of the cross-section.",
      "SEM examination shows increased carbon content along white lines.",
    ],
    nedenler: [
      "Tane sınırı sementit, özellikle %C > 0.8 olan hiperötektoid çeliklerde östenitik bölgeden soğuma sırasında tane sınırlarında oluşan proötektoid sementit fazıdır.",
      "Sıcaklık Acm çizgisi altına düştüğünde tane sınırlarında sementit çökelmeye başlar ve A1'e kadar devam eder. A1 altında östenit → perlit dönüşümüne girer, ancak önceden oluşmuş sementitler tane sınırlarında kalarak zayıf bölgeler oluşturur.",
      "GBC, tel çekme ve yay üretimi gibi işlemlerde çentik etkisi yaratarak kırılmalara yol açar.",
    ],
    nedenler_en: [
      "Grain boundary cementite is a proeutectoid cementite phase formed at grain boundaries during cooling from the austenitic region, especially in hypereutectoid steels with %C > 0.8.",
      "When temperature drops below the Acm line, cementite precipitates at grain boundaries and continues until A1. Below A1, austenite transforms to pearlite, but previously formed cementites remain at grain boundaries creating weak zones.",
      "GBC acts as a stress concentrator in operations like wire drawing and spring manufacturing, leading to fractures.",
    ],
    onleme: [
      "Soğutma hızının optimizasyonu — ek fan, hızlı konveyör kullanımı",
      "C oranının optimize edilmesi (%C ≤ 0.8 hedeflenebilir)",
      "Homojenizasyon tavlaması ile merkez segregasyonlarının dengelenmesi",
      "Serme kafası ve bölgesel soğutmanın kontrol altına alınması",
    ],
    onleme_en: [
      "Optimize cooling rate through additional fans and faster conveyor use",
      "Optimize carbon content (targeting %C ≤ 0.8)",
      "Balance center segregation through homogenization annealing",
      "Control casting head and localized cooling",
    ],
    kaynak: "Altshuler T.L. — The Brittle Fracture of Iron and Steel; Kumar S. — Prevention of GBC during hot rolling of wire rods",
  },
  {
    no: 7,
    slug: "yuzey-alti-sementit",
    category: "wire",
    tr: "Yüzey Altı Sementit",
    en: "Subsurface Cementite Clusters",
    tags: ["sementit", "yüzey altı", "soğuma hızı", "mikrosegregasyon", "yüksek karbon"],
    images: ["image37.jpeg","image38.jpeg","image39.jpeg","image40.jpeg","image41.jpeg","image42.png","image43.png"],
    imgLabels: ["Yüzey altı makro","Sementit öbekleri x100","Optik mikroskop x200","Sementit birikimi","Kesit görünümü","Kırılma yüzeyi","SEM analizi"],
    imgLabels_en: ["Subsurface macroscopic view","Cementite clusters x100","Optical microscopy x200","Cementite accumulation","Cross-section view","Fracture surface","SEM analysis"],
    sikayet: "Tel çekmede kopma veya kırılma / Yay imalatında kopma veya kırılma",
    sikayet_en: "Wire drawing breakage / Spring manufacturing breakage",
    tespitler: [
      "Kangalın yüzeye yakın bölgelerinde sementit öbekleri şeklinde kendini gösterir.",
      "Mikroskop altında 100–200 µm çapında parlak beyaz alanlar şeklinde gözlenir; merkezde görülen sementit yapısından farklı olarak öbekler halindedir.",
      "Bu bölgeler ferrit/perlit matrisine göre ciddi mukavemet farkı oluşturur.",
    ],
    tespitler_en: [
      "Subsurface cementite clusters appear in regions near the wire rod surface.",
      "Under microscopy, they appear as bright white areas 100–200 µm in diameter; unlike the cementite structure seen at center, these exist in cluster form.",
      "These regions create significant strength differential compared to ferrite/pearlite matrix.",
    ],
    nedenler: [
      "Yüksek karbonlu kangallarda ve tellerde yüzeyin hemen altında gözlenen sementit fazı birikimi; sürekli döküm, sıcak haddeleme ve soğuma koşullarına bağlı olarak düşük lokal soğuma hızı ile oluşur.",
      "Kalıntı ve mikrosegregasyon etkisiyle meydana gelir.",
      "Yüzey altı sementit öbekleri, tel çekme işlemi sırasında çentik etkisi yaratarak kırılmalara yol açar.",
    ],
    nedenler_en: [
      "Subsurface cementite phase accumulation observed just below the surface in high-carbon wire rod and wire; forms due to low local cooling rate depending on continuous casting, hot rolling, and cooling conditions.",
      "Develops through residual and microsegregation effects.",
      "Subsurface cementite clusters act as stress concentrators during wire drawing, leading to fractures.",
    ],
    onleme: [
      "Alaşım tasarımında Cr, Mn gibi sementit kararlılığını artıran elementlerin sınırlandırılması",
      "Çelik temizliği ve kalıpta uygun çelik akışı, uygun döküm tozu kullanımı",
      "Tandişte çelik-hava arayüzeyi kontrolü ve oksidasyonun engellenmesi",
    ],
    onleme_en: [
      "Limit cementite-stabilizing elements like Cr and Mn in alloy design",
      "Ensure steel cleanliness and proper steel flow in the mold with appropriate casting powder use",
      "Control steel-air interface in the tundish and prevent oxidation",
    ],
    kaynak: "",
  },
  {
    no: 8,
    slug: "merkezde-bosluk-gbc",
    category: "wire",
    tr: "Merkezde Boşluk ve Tane Sınırı Sementit",
    en: "Centre Void and Grain Boundary Cementite (GBC)",
    tags: ["merkez boşluk", "GBC", "interdendritik", "segregasyon", "13mm"],
    images: ["image44.png","image45.png"],
    imgLabels: ["Kopma yüzeyi makro","Merkez GBC + boşluk x200"],
    imgLabels_en: ["Fracture surface macroscopic","Center GBC + void x200"],
    sikayet: "Yay imalatında (form vermede) kopma veya kırılma",
    sikayet_en: "Spring manufacturing (forming) breakage",
    tespitler: [
      "Yay numunesinde merkeze doğru sivrilen bir kopma yüzeyi görülebilmektedir.",
      "Yapılan mikro incelemede merkez bölgede yoğunlaşan boşluk oluşumları ve bu boşluk oluşumları etrafında tane sınırı sementit yapıları tespit edilmektedir.",
    ],
    tespitler_en: [
      "Spring samples show a fracture surface tapering toward the center.",
      "Cross-sectional microscopy reveals concentrated void formation at the center and grain boundary cementite structures surrounding these voids.",
    ],
    nedenler: [
      "Sürekli döküm ve haddeleme sırasında alaşım elementleri (özellikle C, Mn) merkeze segrege olur. Merkezde karbon oranı yükselince östenit → sementit dönüşüm eğilimi artar.",
      "Özellikle 13 mm çap üzerinde tel çubukta merkez kısım yüzeye göre daha geç soğur; uzun süre Acm–A1 sıcaklık aralığında kalan merkez bölgede sementit tane sınırlarına çöker.",
      "Hem interdendritik shrinkage hem de karbon zenginliği birleştiğinde sementit bu bölgelerde yoğunlaşır.",
    ],
    nedenler_en: [
      "During continuous casting and rolling, alloying elements (especially C and Mn) segregate toward the center. As carbon concentration increases at the center, austenite-to-cementite transformation tendency increases.",
      "Particularly in wire rod above 13 mm diameter, the center cools more slowly than the surface; the center region remaining in the Acm–A1 temperature range for extended periods undergoes cementite precipitation at grain boundaries.",
      "When both interdendritic shrinkage and carbon enrichment combine, cementite becomes concentrated in these regions.",
    ],
    onleme: [
      "Kütük merkez segregasyonunun iyileştirilmesi (uygun superheat ve döküm hızı ayarlaması)",
      "Haddeleme süresince hızlı soğuma, C seviyesinin düşürülmesi",
      "Fan yerleşimi ve konveyör optimizasyonu ile ısıl homojenizasyon",
      "Tel çekme prosesinde kalıp geçiş açılarının çapa göre optimize edilmesi",
    ],
    onleme_en: [
      "Improve ingot center segregation through appropriate superheat and casting speed adjustment",
      "Rapid cooling during rolling and reduction of carbon level",
      "Thermal homogenization through fan placement and conveyor optimization",
      "Optimize die transition angles relative to diameter in wire drawing process",
    ],
    kaynak: "",
  },
  {
    no: 9,
    slug: "makro-inkluzyion",
    category: "wire",
    tr: "Makro İnklüzyon",
    en: "Macro Inclusion",
    tags: ["inklüzyon", "makro", "Ca", "Si", "Al", "Mn", "reoksidasyon", "SEM-EDS"],
    images: ["image46.jpeg","image47.jpeg","image48.jpeg","image49.png","image50.png","image51.jpeg"],
    imgLabels: ["Kopma yüzeyi makro","Optik mikroskop x100","İnklüzyon kümesi","SEM görüntüsü","EDS spektrumu","Optik x500"],
    imgLabels_en: ["Fracture surface macroscopic","Optical microscopy x100","Inclusion cluster","SEM image","EDS spectrum","Optical x500"],
    sikayet: "Tel çekmede kopma veya kırılma / Yay imalatında kopma veya kırılma",
    sikayet_en: "Wire drawing breakage / Spring manufacturing breakage",
    tespitler: [
      "Kırılma yüzeyinde kesitten yapılan mikro inceleme ile tespit edilebilmektedir.",
      "İnklüzyon boyutuna bağlı olarak kırılma yüzeyinde genellikle gevrek bir kırılma şekli kendini göstermektedir.",
      "Optik mikroskopta koyu gri/siyah dağınık veya yığılmış parçalar halinde gözükür.",
      "SEM/EDS analizi: inklüzyon bölgelerinde Ca, Si, O, Na, Al, Mn, F, Mg elementlerinin varlığı tespit edilmiştir.",
    ],
    tespitler_en: [
      "Detected through cross-sectional microscopy of fracture surfaces.",
      "Depending on inclusion size, fracture surfaces typically exhibit brittle fracture characteristics.",
      "Under optical microscopy, inclusions appear as dark gray/black scattered or clustered particles.",
      "SEM/EDS analysis confirms the presence of Ca, Si, O, Na, Al, Mn, F, and Mg elements in inclusion regions.",
    ],
    nedenler: [
      "Yeniden oksitlenme (reoxidation)",
      "Girdap oluşumu (pota ve tandiş doldurma, argonla karıştırma)",
      "Çelik ve refrakter reaksiyonları (erozyon, korozyon)",
      "Döküm sırasında meydana gelen erozyon ve inklüzyon topaklanması",
    ],
    nedenler_en: [
      "Reoxidation",
      "Vortex formation (ladle and tundish filling, argon stirring)",
      "Steel and refractory reactions (erosion, corrosion)",
      "Erosion and inclusion clustering during casting",
    ],
    onleme: [
      "Sürekli döküm kalıp seviye kontrolü",
      "Uygun viskoziteli döküm tozu kullanımı",
      "Pota istasyonunda Ca enjeksiyonu ve inklüzyon modifikasyonu, alttan karıştırma",
    ],
    onleme_en: [
      "Control mold level in continuous casting",
      "Use casting powder with appropriate viscosity",
      "Calcium injection and inclusion modification at ladle station with bottom stirring",
    ],
    kaynak: "",
  },
  {
    no: 10,
    slug: "chevron-merkez-catlak",
    category: "wire",
    tr: "Merkezde Çatlak — Chevron Kusuru",
    en: "Central Bursting — Chevron Defect",
    tags: ["chevron", "merkez çatlak", "V çatlak", "GBC", "bainit", "segregasyon"],
    images: ["image52.jpeg","image53.jpeg","image54.jpeg","image55.jpeg","image56.jpeg","image57.jpeg"],
    imgLabels: ["Optik x25 (tel)","Optik x500","Optik x200","V-tipi chevron","GBC çevresi","Bainit sert faz"],
    imgLabels_en: ["Optical x25 (wire)","Optical x500","Optical x200","V-type chevron","GBC vicinity","Bainite hard phase"],
    sikayet: "Tel çekmede kopma veya kırılma / Yay imalatında kopma veya kırılma",
    sikayet_en: "Wire drawing breakage / Spring manufacturing breakage",
    tespitler: [
      "Kangal yüzeyindeki periyodik açık renkli izler tel merkezinde chevron tipi çatlak oluşumuna işaret edebilir.",
      "Malzemenin merkez noktasında üçgen biçimli haddeleme yönüne doğru uzamış boşluklar Chevron Kusuru olarak tanımlanır.",
      "Mikroyapıda telin merkez ekseni boyunca 'V' şeklinde yırtılma görülmektedir. V'nin kapalı uç noktası tel çekme yönüne doğru hizalanır.",
      "Çatlak çevresinde GBC ve bainit gibi sert fazlar tespit edilmiştir.",
    ],
    tespitler_en: [
      "Periodic light-colored marks on wire rod surface may indicate chevron-type crack formation at wire center.",
      "Triangular voids in the material center extending along the rolling direction are defined as Chevron Defect.",
      "Microstructure shows 'V'-shaped tearing along the wire center axis, with the closed end of the V aligned along the wire drawing direction.",
      "Hard phases such as GBC and bainite are detected around cracks.",
    ],
    nedenler: [
      "Chevron tipi çatlaklar; malzemenin iç yapısındaki gerilim birikimi, mikro yapı düzensizlikleri ve/veya çekme sırasında oluşan plastik deformasyon dengesizliklerinden kaynaklanır.",
      "Merkez segregasyonu (C, Mn, S, P), interdendritik shrinkage ve içyapıda mevcut sert fazlar (GBC, bainit) chevron çatlakların başlama noktaları olarak işlev görür.",
      "Tel çekme kalıp geometrisi (matris açısı, redüksiyon oranı) ve yetersiz yağlama da kusur oluşumunu tetikler.",
    ],
    nedenler_en: [
      "Chevron-type cracks originate from stress accumulation in internal structure, microstructural irregularities, and/or imbalanced plastic deformation during drawing.",
      "Center segregation (C, Mn, S, P), interdendritic shrinkage, and hard phases in the internal structure (GBC, bainite) serve as initiation points for chevron cracks.",
      "Wire drawing die geometry (matrix angle, reduction ratio) and inadequate lubrication also trigger defect formation.",
    ],
    onleme: [
      "Merkez segregasyonu azaltmak için S, P ve C kontrolleri",
      "Soft reduction ve EMS uygulamaları",
      "Döküm hız ve sıcaklık kontrolü (uniform soğuma)",
      "Dengeli hadde geçişleri ve tel çekmede matris açı/oran optimizasyonu",
      "Çok kademeli çekme, düşük deformasyon oranı, ara tavlamalarla iç gerilim giderilmesi",
    ],
    onleme_en: [
      "Control S, P, and C to reduce center segregation",
      "Apply soft reduction and EMS techniques",
      "Control casting speed and temperature (uniform cooling)",
      "Balanced rolling passes and die geometry/reduction ratio optimization in wire drawing",
      "Multi-stage drawing with low deformation ratios and intermediate annealing to relieve internal stress",
    ],
    kaynak: "ISIJ International — Formation Mechanism of Chevron Cracks in High Carbon Steel Wire Rods; ASM Handbook Volume 9",
  },
  {
    no: 11,
    slug: "sert-faz-martenzit",
    category: "wire",
    tr: "Sert Faz — Martenzit",
    en: "Hard Phase — Martensite",
    tags: ["martenzit", "BCT", "difüzyonsuz", "HV 700-800", "ani soğuma", "yüksek karbon"],
    images: ["image58.png","image59.jpeg","image60.jpeg"],
    imgLabels: ["Optik x100 kenar","Optik x200 merkez","Optik x500 iğne martenzit"],
    imgLabels_en: ["Optical x100 edge","Optical x200 center","Optical x500 needle martensite"],
    sikayet: "Tel çekmede kopma veya kırılma / Yay imalatında kopma veya kırılma",
    sikayet_en: "Wire drawing breakage / Spring manufacturing breakage",
    tespitler: [
      "Kangal ve tel kırılma yüzeyi tamamen gevrektir. Malzeme doğrultmaya girmeden hatta elle bile kırılabilir.",
      "Yüksek karbonlu kalitelerde görülmesi olasıdır. Mikro yapı incelemesi gereklidir.",
      "Tipik 'iğne' ya da 'paket' (lath/plate) formundaki martenzit ışık altında parlak ve mavimsi-gümüş renkte görünür.",
      "Sertlik değeri 700–800 HV'ye kadar çıkabilir.",
    ],
    tespitler_en: [
      "Wire rod and wire fracture surfaces are completely brittle. Material breaks even without straightening, sometimes by hand.",
      "Likely to occur in high-carbon grades; microstructural examination is necessary.",
      "Typical 'needle' or 'packet' (lath/plate) form martensite appears bright and bluish-silver under light.",
      "Hardness can reach 700–800 HV.",
    ],
    nedenler: [
      "Yüksek karbonlu çeliklerde (%0.6–1.2 C) haddeleme aşamasında ani soğuma şartlarıyla difüzyonsuz faz dönüşümü gerçekleşir.",
      "Karbon atomları difüzyon yapamadan austenit kafesinde sıkışır → tetragonal (BCT) yapı oluşur.",
      "Oluşan martenzit sert (700–800 HV), kırılgan ve kararsız bir yapıdır.",
    ],
    nedenler_en: [
      "In high-carbon steels (%0.6–1.2 C), diffusionless phase transformation occurs during rolling under rapid cooling conditions.",
      "Carbon atoms become trapped in the austenite lattice without diffusing, forming a tetragonal (BCT) structure.",
      "The resulting martensite is hard (700–800 HV), brittle, and unstable.",
    ],
    onleme: [
      "Normalize veya tavlama sonrası hava soğutması uygulanmalı",
      "Yüksek karbonlu tel ve yaylık çeliklerde karbürleri küreselleştirerek martenzit oluşumu önlenmeli",
      "Östenitleme sıcaklığı düşürülerek kararlı ferrit/perlit yapısı sağlanabilir",
      "Mn, Cr, Mo gibi elementlerin miktarı kontrol edilerek martenzit eğilimi azaltılır",
      "Haddeleme aşamasında ani soğuma yaratacak su ve hava akışından kaçınılmalıdır",
    ],
    onleme_en: [
      "Apply air cooling after normalization or annealing",
      "Prevent martensite formation in high-carbon wire and spring steels through cementite spheroidization",
      "Lower austenitization temperature to ensure stable ferrite/pearlite structure",
      "Control the amount of Mn, Cr, Mo elements to reduce martensite tendency",
      "Avoid rapid cooling water and air flow during rolling to prevent martensite formation",
    ],
    kaynak: "Krauss G. — Steels: Processing, Structure, and Performance; ASM Handbook Vol 4: Heat Treating",
  },

  // ─── YASSI MAMUL — FLAT PRODUCT / COIL ───────────────────
  {
    no: 12,
    slug: "kaynak-haz-catlak-inkluzyion",
    category: "flat",
    tr: "Kaynak Bölgesinde Çatlak — İnklüzyon",
    en: "Crack in HAZ (Welding) — Inclusion",
    tags: ["HAZ", "kaynak", "MnS", "Al₂O₃", "SEM-EDS", "jant", "bobin"],
    images: ["image61.jpeg","image62.jpeg","image63.jpeg","image64.png"],
    imgLabels: ["Makro HAZ çatlak","Optik mikroskop x100","MnS inklüzyon","SEM-EDS analizi"],
    imgLabels_en: ["Macroscopic HAZ crack","Optical microscopy x100","MnS inclusion","SEM-EDS analysis"],
    sikayet: "Çatlak — Kabuk Şikayetleri",
    sikayet_en: "Crack — Shell Complaints",
    tespitler: [
      "HAZ bölgesinde kılcal çatlak olarak gözle görülebilmektedir.",
      "İncelenen örnekte kaynak bölgesinde (HAZ) yüzeye açık kılcal çatlaklar tespit edilmiştir.",
      "Çatlakların ekseni boyunca Mn ve S elementleri içeren inklüzyon kümelenmeleri gözlemlenmiş, SEM-EDS analizleri ile doğrulanmıştır.",
    ],
    tespitler_en: [
      "Capillary cracks are visible in the HAZ region.",
      "Capillary cracks open to the surface are detected in the weld region (HAZ) of the examined sample.",
      "Inclusion clusters containing Mn and S elements are observed along crack axes and confirmed by SEM-EDS analyses.",
    ],
    nedenler: [
      "Bu tür inklüzyonlar; deoksidasyon yetersizliği, tundish/torpido içi refrakter bozunması veya uygun olmayan ergitme koşulları gibi sebeplerle oluşabilir.",
      "Isı girdisi altında kalan HAZ bölgesinde tane sınırlarında gerilim birikir; MnS ve benzeri düşük erime noktalı inklüzyonların çevresinde çatlak başlatıcı görevi görür.",
    ],
    nedenler_en: [
      "Such inclusions may form due to insufficient deoxidation, refractory degradation inside tundish/torpedo, or inappropriate melting conditions.",
      "In the HAZ region under heat input, stress accumulates at grain boundaries; MnS and similar low-melting-point inclusions serve as crack initiators.",
    ],
    onleme: [
      "İnklüzyon kontrolü için temiz çelik üretim uygulamaları (Ca-treatment, argon stirring)",
      "MnS ve Al₂O₃ inklüzyonlarının önüne geçmek amacıyla ikincil metalürji süreçleri optimize edilmeli",
      "Kaynak bölgesine uygun düşük sülfürlü ve düşük inklüzyon içerikli çelik kaliteleri tercih edilmeli",
      "Kaynak öncesi ve sırasında ısıl işlemler ile iç gerilimler azaltılmalı",
    ],
    onleme_en: [
      "Clean steel production practices for inclusion control (Ca-treatment, argon stirring)",
      "Optimize secondary metallurgy processes to prevent MnS and Al₂O₃ inclusions",
      "Prefer low-sulfur and low-inclusion steel grades suitable for weld regions",
      "Reduce internal stresses through thermal treatments before and during welding",
    ],
    kaynak: "",
  },
  {
    no: 13,
    slug: "lokal-sertlik",
    category: "flat",
    tr: "Lokal Sertlik",
    en: "Local Hardness Variation",
    tags: ["lokal sertlik", "su spreyi", "soğutma", "perlit", "ferrit", "boru", "profil"],
    images: ["image65.png","image66.png","image67.jpeg"],
    imgLabels: ["Form kusuru makro","Mikro yapı karşılaştırma","Sertlik haritalama"],
    imgLabels_en: ["Shape defect macroscopic","Microstructure comparison","Hardness mapping"],
    sikayet: "Lokal Sertlik Problemi",
    sikayet_en: "Local Hardness Problem",
    tespitler: [
      "Bobinden boru veya profil üretimi sırasında şekil almayan düz kalan bölgeler kendini göstermektedir.",
      "Hızlı soğuyan bölgelerde ince perlit yapısı ağırlık gösterirken yavaş soğuyan bölgelerde ferrit fazı daha sık görülür.",
      "Hızlı soğuyan ve düzleşme görülmemiş bölgeler daha yüksek sertlik (HV) gösterir.",
    ],
    tespitler_en: [
      "Regions that remain flat without shape formation during pipe or profile production from coil are evident.",
      "Fine pearlite structure predominates in rapidly cooled regions while ferrite phase is more frequently observed in slowly cooled regions.",
      "Rapidly cooled regions without flattening show higher hardness (HV).",
    ],
    nedenler: [
      "Sıcak haddeleme sonrası homojen olmayan su spreyi uygulamaları veya yetersiz soğutma (su jeti arızası, düzensiz debi, kirli nozul) malzeme üzerinde lokal soğuma hız farklarına neden olur.",
      "Farklılıklar mikro yapıda perlitik ve ferritik faz oranlarının değişmesiyle sonuçlanır.",
    ],
    nedenler_en: [
      "Non-uniform water spray application after hot rolling or insufficient cooling (water jet malfunction, irregular flow rate, clogged nozzle) causes local cooling rate differences on the material.",
      "These differences result in changes in pearlitic and ferritic phase ratios in the microstructure.",
    ],
    onleme: [
      "Hattaki tüm su nozullarının basınç ve debi kontrolleri periyodik olarak yapılmalı",
      "Tüm yüzeye homojen su dağılımı sağlanmalı; nozul konumlandırmaları optimize edilmeli",
      "Termal kamera veya yüzey sıcaklık ölçüm sistemleri ile gerçek zamanlı kontrol",
    ],
    onleme_en: [
      "Perform periodic pressure and flow rate checks on all water nozzles on the line",
      "Ensure uniform water distribution to all surfaces; optimize nozzle positioning",
      "Real-time control through thermal cameras or surface temperature measurement systems",
    ],
    kaynak: "ASM Handbook, Volume 4A — Steel Heat Treating Fundamentals and Processes",
  },
  {
    no: 14,
    slug: "yirtilma-bukme",
    category: "flat",
    tr: "Yırtılma — Bükme Prosesi",
    en: "Tearing — Bending Process",
    tags: ["yırtılma", "bükme", "R/t oranı", "perlit bandı", "dış bükey", "DIN EN ISO 7438"],
    images: ["image68.png","image69.jpeg","image70.jpeg","image71.jpeg"],
    imgLabels: ["Makro çatlak görünüm","Yırtılma bölgesi","Büküm radyüsü","Optik mikroskop detay"],
    imgLabels_en: ["Macroscopic crack view","Tear region","Bend radius","Optical microscopy detail"],
    sikayet: "Büküm esnasında yırtılma/çatlama",
    sikayet_en: "Tearing/cracking during bending",
    tespitler: [
      "Form verilmiş numunede dış bükey köşelerde çatlak oluşumları gözlenir.",
      "Çatlak bölgenin iç bükey kısmında keskin dayama izine rastlanabilir.",
      "Çatlak bölge başlangıç ve bitiş noktalarında mikro yapı incelemesi ile çeliğin mekanik özelliklerinin prosese uygunluğu değerlendirilmelidir.",
    ],
    tespitler_en: [
      "Crack formation is observed at outer convex corners of shaped samples.",
      "Sharp loading marks are found in the inner concave region of crack zones.",
      "Microstructural examination at crack initiation and termination points should evaluate the compatibility of steel mechanical properties with the process.",
    ],
    nedenler: [
      "Bükme işlemi sırasında malzemenin dış bükey yüzeyinde çekme gerilmesi, iç bükey yüzeyinde basma gerilmesi oluşur. En büyük şekil değişimi dış tarafta oluşur.",
      "Malzemenin süneklik sınırı aşılırsa mikroyapıdaki zayıf bölgelerde (tane sınırları, inklüzyonlar, bant yapılar) çatlak başlar.",
      "Çekme gerilmesi yönüne dik lamelli yapı (perlit bantları) varsa gerilmeyi absorbe edemez; çatlak ilerler.",
      "Küçük yarıçaplı bükmeler: R/t oranı azaldıkça gerilme ve deformasyon artar.",
    ],
    nedenler_en: [
      "During bending, tensile stress develops on the outer convex surface and compressive stress on the inner concave surface. Maximum shape change occurs on the outside.",
      "If material ductility limit is exceeded, cracks initiate at weak microstructural regions (grain boundaries, inclusions, banded structures).",
      "If lamellar structure (pearlite bands) is perpendicular to tensile stress direction, it cannot absorb the stress; cracks propagate.",
      "For small-radius bends: as R/t ratio decreases, stress and deformation increase.",
    ],
    onleme: [
      "Homojen ferrit-perlit dağılımı ile sünekliğin artırılması; perlit bantlarının minimize edilmesi",
      "Katlamaya uygun çelik kalitesi ve inklüzyon kontrolü",
      "Bükme yarıçapı malzeme kalınlığının en az 2–3 katı olacak şekilde seçilmeli",
      "Soğuk şekillendirmede yüksek deformasyon oranlarından kaçınılmalı; gerekirse ara tavlama",
    ],
    onleme_en: [
      "Increase ductility through homogeneous ferrite-pearlite distribution; minimize pearlite bands",
      "Select appropriate steel quality and control inclusions for bending",
      "Select bend radius to be at least 2–3 times material thickness",
      "Avoid high deformation ratios in cold forming; apply intermediate annealing if necessary",
    ],
    kaynak: "DIN EN ISO 7438 — Bükme testi standardı; ASM Handbook Volume 14B — Sheet Forming Fundamentals",
  },
  {
    no: 15,
    slug: "laminasyon",
    category: "flat",
    tr: "Laminasyon",
    en: "Lamination",
    tags: ["laminasyon", "shrinkage", "segregasyon", "EMS", "soft reduction", "merkez"],
    images: ["image52.jpeg","image53.jpeg","image54.jpeg","image72.png","image73.jpeg","image74.jpeg"],
    imgLabels: ["Laminasyon makro","Kesit optik x100","Merkez süreksizlik","Optik x200","İç boşluklar","SEM görüntüsü"],
    imgLabels_en: ["Lamination macroscopic","Cross-section optical x100","Center discontinuity","Optical x200","Internal voids","SEM image"],
    sikayet: "Bobin merkezinde boşluk/laminasyon",
    sikayet_en: "Void/lamination at coil center",
    tespitler: [
      "Çelik ürünlerin merkezinde veya tabaka geçişlerinde gözlemlenen lamelli boşluklar ve çatlak benzeri süreksizlikler şeklinde ortaya çıkar.",
      "Döküm sırasında oluşan hapsolan gazlar, segregasyonlar, merkez büzülme boşlukları (shrinkage cavities) nedeniyle oluşur.",
      "Özellikle kesme, punch veya dilme işlemlerinde gözle görülür hale gelir.",
    ],
    tespitler_en: [
      "Laminar voids and crack-like discontinuities appear at the center or layer interfaces of steel products.",
      "Results from trapped gases, segregation, and center shrinkage cavities formed during casting.",
      "Becomes visible to the eye particularly during cutting, punching, or slitting operations.",
    ],
    nedenler: [
      "Döküm sırasında hapsolan gazlar, kimyasal segregasyonlar ve merkez beslemesinin yetersizliği laminar süreksizlikler oluşturur.",
      "MnS, Al₂O₃ gibi inklüzyonlar da bu bölgelerde birikerek süreksizliklere katkıda bulunur.",
    ],
    nedenler_en: [
      "Trapped gases, chemical segregation, and insufficient center feeding during casting create laminar discontinuities.",
      "Inclusions such as MnS and Al₂O₃ accumulate in these regions and contribute to discontinuities.",
    ],
    onleme: [
      "Dökümde alttan karıştırma ile inklüzyon modifikasyonu",
      "Sürekli dökümlerde soft reduction ve EMS kullanımı",
      "Optimum superheat sıcaklığı ve tundish/kalıp sıcaklık kontrolü",
      "Kimyasal bileşimdeki P, S elementlerinin sınırlandırılması",
    ],
    onleme_en: [
      "Inclusion modification through bottom stirring in casting",
      "Use soft reduction and EMS in continuous casting",
      "Optimize superheat temperature and control tundish/mold temperature",
      "Limit P and S elements in chemical composition",
    ],
    kaynak: "Totten G.E. — Steel Heat Treatment: Metallurgy and Technologies; ASM Handbook, Volume 1; Dieter G.E. — Mechanical Metallurgy",
  },
  {
    no: 16,
    slug: "kabuk-makro-inkluzyion-1",
    category: "flat",
    tr: "Kabuk, Makro İnklüzyon (Vaka 1)",
    en: "Sliver, Macro Inclusion — Case 1",
    tags: ["kabuk", "sliver", "inklüzyon", "FeO", "iç oksidasyon", "hadde"],
    images: ["image75.png","image76.png"],
    imgLabels: ["Makro x10","Optik mikroskop x100"],
    imgLabels_en: ["Macro x10","Optical microscopy x100"],
    sikayet: "Çizik, kabuk",
    sikayet_en: "Scratch, sliver",
    tespitler: [
      "Kusur yassı mamül hammadde yüzeyinde gözle ayırt edilebilmektedir. Düz çizgi şeklinde veya parçalı şekilde ele gelen bir ayrıntıdır.",
      "Mikro incelemede iç oksidasyon tespit edilmesi durumunda sürekli döküm parametreleri gözden geçirilmelidir.",
      "İç oksidasyon tespit edilmediği durumda muhtemelen FeO varlığı görülür; sıcak haddeleme sürecinde etkenler değerlendirilmelidir.",
    ],
    tespitler_en: [
      "Defect is visible to the eye on flat product feedstock surface. It is a detail appearing as a straight line or broken sections.",
      "If internal oxidation is detected in microscopy, continuous casting parameters should be reviewed.",
      "If internal oxidation is not detected, FeO presence is likely observed; factors in the hot rolling process should be evaluated.",
    ],
    nedenler: [
      "Kabuk kusurları, döküm sırasında yüzeyde oluşan mikroskopik çatlakların haddeleme sırasında açılmasıyla meydana gelir.",
      "Bu çatlaklar genellikle yüzey segregasyonu, MnS yönelmesi veya kalıntı inklüzyonların yüzeye çıkmasıyla ilişkilidir.",
    ],
    nedenler_en: [
      "Shell defects form when microscopic cracks on the surface during casting open during rolling.",
      "These cracks are typically associated with surface segregation, MnS orientation, or residual inclusions surfacing.",
    ],
    onleme: [
      "Sürekli dökümde kalıp içi sıcaklık kontrolü, soğutma koşulları ve kalıp tozu kullanımı",
      "Slab yüzey muayenesi; yüzey ve kenarlarında çatlak olmadığından emin olunmalı",
      "Merdane yüzeyleri düzenli olarak kontrol edilmeli",
      "Yüksek basınçlı su jeti ile etkin tufal temizliği",
    ],
    onleme_en: [
      "Control mold temperature, cooling conditions, and casting powder use in continuous casting",
      "Inspect slab surface; ensure no cracks on surface and edges",
      "Regularly inspect roll surfaces",
      "Effective scale removal with high-pressure water jetting",
    ],
    kaynak: "Hasse D. — Surface Quality in Hot Rolling of Steel, Iron & Steel Technology 2015; ASM Handbook, Volume 14A",
  },
  {
    no: 17,
    slug: "oyuklanma-cukurcuk",
    category: "flat",
    tr: "Oyuklanma, Çukurcuk",
    en: "Pitting, Surface Corrosion",
    tags: ["oyuklanma", "çukurcuk", "pitting", "MnS", "Al₂O₃", "korozyon", "depolama"],
    images: [],
    imgLabels: [],
    imgLabels_en: [],
    sikayet: "Yüzeyde çukurcuk, oyuklanma, yüzey kusuru",
    sikayet_en: "Surface pitting, pitting corrosion, surface defect",
    tespitler: [
      "Kusur yassı mamül yüzeyinde gözle görülebilmekte olup el ile kontrolünde çukurcuk oluşumu hissi vermektedir.",
      "Makro ve mikroskopik görüntülerde yüzeyde düzensiz, yuvarlak kenarlı çukurlanmalar ve lokal renk değişimleri gözlemlenmektedir.",
      "Kusurun derinliği mikroskop altında ölçülmelidir.",
    ],
    tespitler_en: [
      "Defect is visible to the eye on flat product surface and gives the sensation of pitting when touched.",
      "Irregular, rounded-edge depressions and local color variations are observed on the surface in macro and microscopic views.",
      "Defect depth should be measured under microscopy.",
    ],
    nedenler: [
      "Üretim kaynaklı: Yüzey inklüzyonları (MnS, Al₂O₃, CaO) — haddeleme sırasında yüzeye yakın inklüzyonlar çıkarak lokal boşluk bırakır.",
      "Üretim kaynaklı: Gaz boşlukları (pinhole) — sürekli döküm sırasında sıkışan gazlar yüzeye yakın kalıp haddelenirken çukur haline gelir.",
      "Korozyon kaynaklı: Nemli veya asidik ortamda depolama; deniz kenarında ve gemi sevkiyatlarında paslanma.",
    ],
    nedenler_en: [
      "Production-related: Surface inclusions (MnS, Al₂O₃, CaO) — inclusions near surface emerge during rolling, leaving local voids.",
      "Production-related: Gas voids (pinholes) — gases trapped during continuous casting become pits when the near-surface mold is rolled.",
      "Corrosion-related: Storage in humid or acidic environments; rusting in coastal areas and maritime shipments.",
    ],
    onleme: [
      "Üretim aşamasında inklüzyon kontrolü ve çelik temizliği",
      "Gaz entrapmanını azaltacak döküm parametrelerinin optimizasyonu",
      "Etkin tufal giderme (descaling)",
      "Uygun depolama ve sevkiyat koşulları (nem kontrolü, koruyucu kaplama)",
    ],
    onleme_en: [
      "Inclusion control and steel cleanliness at production stage",
      "Optimize casting parameters to reduce gas entrapment",
      "Effective scale removal (descaling)",
      "Appropriate storage and shipment conditions (moisture control, protective coating)",
    ],
    kaynak: "ISO 8402 / ASTM G46; ASM Handbook, Volume 5: Surface Engineering",
  },
  {
    no: 18,
    slug: "tufal-kabuk-a",
    category: "flat",
    tr: "Tufal, Kabuk — Vaka A",
    en: "Scale and Shell Defect — Case A",
    tags: ["tufal", "kabuk", "oksit", "descaling", "haddeleme", "FeO"],
    images: [],
    imgLabels: [],
    imgLabels_en: [],
    sikayet: "Yüzey bozukluğu, tufal veya kabuk oluşumu",
    sikayet_en: "Surface degradation, scale or shell formation",
    tespitler: [
      "Optik mikroskop görüntüsünde yüzey altına gömülmüş oksit kalıntıları çelik matriste siyah renkli düzensiz alanlar şeklinde görünür.",
      "Tufal kabuğu ile metal matrisi arasında yapışma zayıf olduğundan bu bölgeler ilerleyen işlemlerde yüzeyden ayrılabilir.",
      "Kusur altında SEM-EDS analizi yapılması gerekir; genellikle demir oksit veya çelik üretim kaynaklı kalıntı ile karşılaşılmaktadır.",
    ],
    tespitler_en: [
      "In optical microscopy, oxide residues embedded subsurface appear as black irregular areas in the steel matrix.",
      "Adhesion between scale shell and metal matrix is weak, so these regions can separate from the surface in subsequent operations.",
      "SEM-EDS analysis below the defect is necessary; typically encounters iron oxides or steel production-derived residue.",
    ],
    nedenler: [
      "Yetersiz tufal temizliği (descaling) veya yüksek tufal birikimi",
      "Fırın atmosferinde fazla oksidasyon (özellikle yüksek sıcaklıkta uzun süre bekleme)",
      "Döküm sonrası yüzey kalıntıları (MnS, Al₂O₃, FeOₓ)",
      "Sert tufal tabakalarının hadde merdaneleriyle yassılaştırılarak yüzeye gömülmesi",
    ],
    nedenler_en: [
      "Insufficient scale removal (descaling) or excessive scale buildup",
      "Excessive oxidation in furnace atmosphere (especially prolonged exposure at high temperature)",
      "Post-casting surface residues (MnS, Al₂O₃, FeOₓ)",
      "Hard scale layers flattened by rolling rolls and embedded into the surface",
    ],
    onleme: [
      "Etkin birincil ve ikincil tufal giderme",
      "Fırın sıcaklığı ve tutma süresi kontrolü",
      "Merdane yüzeyi kontrolü ve kalitesi",
    ],
    onleme_en: [
      "Effective primary and secondary scale removal",
      "Control furnace temperature and holding time",
      "Control and maintain roll surface quality",
    ],
    kaynak: "ASM Handbook, Volume 1; Roberts W.L. — Hot Rolling of Steel",
  },
  {
    no: 19,
    slug: "tufal-kabuk-b",
    category: "flat",
    tr: "Tufal, Kabuk — Vaka B",
    en: "Scale and Shell Defect — Case B (SEM Confirmed)",
    tags: ["tufal", "kabuk", "FeO", "Fe₃O₄", "Fe₂O₃", "SEM-EDS", "ISIJ"],
    images: [],
    imgLabels: [],
    imgLabels_en: [],
    sikayet: "Yüzey bozukluğu, tufal veya kabuk oluşumu",
    sikayet_en: "Surface degradation, scale or shell formation",
    tespitler: [
      "Yüzeyde lokal koyu renkli, pullanmış veya kabarmış alanlar gözlenmektedir.",
      "Optik Mikroskop (X25+): Yüzey altında uzanan siyah renkli kalın ve düzensiz bir tabaka — demir oksitlerin (FeO, Fe₃O₄, Fe₂O₃) mekanik olarak gömülmesiyle oluşmuştur.",
      "Bazı bölgelerde mikro çatlakların başlangıcı görülür. SEM-EDS analizi ile oksit tabakası bileşimi doğrulanmıştır.",
    ],
    tespitler_en: [
      "Local dark-colored, flaking, or blistered regions are observed on the surface.",
      "Optical Microscopy (X25+): A thick, black, irregular layer extending subsurface — formed by mechanical embedding of iron oxides (FeO, Fe₃O₄, Fe₂O₃).",
      "Initiation of micro-cracks is visible in some regions. SEM-EDS analysis confirms oxide layer composition.",
    ],
    nedenler: [
      "Sıcak haddeleme sırasında yeterince temizlenmeyen oksit tabakalarının çelik yüzeyine gömülmesi.",
      "Yetersiz tufal temizliği, uzun fırın bekleme süreleri, döküm sonrası yüzey kalıntıları.",
    ],
    nedenler_en: [
      "Mechanical embedding of incompletely cleaned oxide layers into steel surface during hot rolling.",
      "Insufficient scale removal, prolonged furnace dwell times, post-casting surface residues.",
    ],
    onleme: [
      "Etkin birincil ve ikincil tufal giderme",
      "Fırın sıcaklık ve süre kontrolü",
      "Merdane yüzey kalitesinin korunması",
    ],
    onleme_en: [
      "Effective primary and secondary scale removal",
      "Control furnace temperature and dwell time",
      "Maintain roll surface quality",
    ],
    kaynak: "Sasaki Y. et al. — Scale Defect Formation and Control in Hot Strip Rolling, ISIJ Int. 2004",
  },
  {
    no: 20,
    slug: "yirtilma-delik-acma",
    category: "flat",
    tr: "Yırtılma — Delik Açma Prosesi",
    en: "Tearing — Blanking / Punching Process",
    tags: ["yırtılma", "blanking", "delik açma", "punç", "kesme boşluğu", "mikroalaşımlı"],
    images: [],
    imgLabels: [],
    imgLabels_en: [],
    sikayet: "Bağlantı delikleri etrafında çatlak ve yırtılma problemleri",
    sikayet_en: "Crack and tearing problems around connection holes",
    tespitler: [
      "Düz saclarda delik açma prosesinde görülen bu kusur, kesim sonrası koparma noktası başlangıcında ayrılma olarak kendini gösterir.",
      "Genellikle mikro alaşımlı yüksek mukavemetli çeliklerde görülür.",
    ],
    tespitler_en: [
      "This defect observed in hole-punching operations on flat sheets manifests as separation at crack initiation after shearing.",
      "Typically observed in microalloyed high-strength steels.",
    ],
    nedenler: [
      "Blanking işleminde plastik deformasyon tamamlanmadan kırılma gerçekleşirse yırtılma bölgesi boyunca düzensiz çatlaklar oluşur.",
      "Yüksek sertliğe sahip martenzitik yapılar, yüzey altı sementit öbekleri ya da MnS, TiN inklüzyonları çatlak başlatıcı görevi görür.",
      "Kalıp-punç boşluğu çok dar veya bıçaklar körelmişse düzgün kesme gerçekleşemez.",
    ],
    nedenler_en: [
      "If fracture occurs before plastic deformation is complete in blanking, irregular cracks form across the sheared region.",
      "Martensitic structures with high hardness, subsurface cementite clusters, or MnS and TiN inclusions serve as crack initiators.",
      "If punch-die clearance is too tight or blades are dull, clean shearing cannot occur.",
    ],
    onleme: [
      "Ferrit + ince perlit tercih edilmeli (IF kalite, düşük karbonlu saclar)",
      "Yüksek mukavemetli çeliklerde kesme boşluğu (clearance) %5–10 optimize edilmeli",
      "Kalıp/punç yüzeyi düzgün ve keskin olmalı; bıçaklar düzenli kontrol edilmeli",
    ],
    onleme_en: [
      "Prefer ferrite + fine pearlite (IF grade, low-carbon sheets)",
      "Optimize shear clearance (clearance) to 5–10% in high-strength steels",
      "Punch/die surface must be smooth and sharp; blades must be regularly inspected",
    ],
    kaynak: "ASM Handbook, Cilt 7",
  },
  {
    no: 21,
    slug: "kabuk-sem-eds",
    category: "flat",
    tr: "Kabuk — SEM-EDS Doğrulamalı",
    en: "Shell Defect — SEM-EDS Confirmed",
    tags: ["kabuk", "SEM-EDS", "80µm", "Si", "Na", "Ca", "Mg", "Zr", "mold flux"],
    images: [],
    imgLabels: [],
    imgLabels_en: [],
    sikayet: "Yüzey bozukluğu, tufal veya kabuk oluşumu, yüzeyde kabuk atması",
    sikayet_en: "Surface degradation, scale or shell formation, shell shedding on surface",
    tespitler: [
      "Makro incelemelerde yüzeyden ince bir kabuk tabakasının ayrıldığı gözlenmiştir.",
      "SEM/EDS incelemelerinde kusurun yaklaşık 80 µm derinlikte yüzey altında uzadığı görülmüştür.",
      "Kabuk altında metalik olmayan kalıntılar tespit edilmiş; SEM/EDS analizlerinde O, Si, Na, Ca, Mg, Zr, Al ve Mn elementleri doğrulanmıştır.",
      "Bu element profili refrakter/mold flux kaynaklı kalıntıların varlığına işaret etmektedir.",
    ],
    tespitler_en: [
      "Macro examination reveals a thin shell layer separating from the surface.",
      "SEM/EDS examination shows the defect extends subsurface to approximately 80 µm depth.",
      "Non-metallic residues detected beneath the shell; SEM/EDS analysis confirms O, Si, Na, Ca, Mg, Zr, Al, and Mn elements.",
      "This element profile indicates the presence of refractory/mold flux-derived residues.",
    ],
    nedenler: [
      "Mold flux veya refrakter kaynaklı karmaşık kalıntı profili (O, Si, Na, Ca, Mg, Zr, Al, Mn) sürekli döküm aşamasındaki kirliliği düşündürmektedir.",
      "Yetersiz descaling ve sert tufal tabakalarının merdanelerle yüzeye gömülmesi.",
    ],
    nedenler_en: [
      "Complex residue profile from mold flux or refractory (O, Si, Na, Ca, Mg, Zr, Al, Mn) suggests contamination during continuous casting stage.",
      "Insufficient descaling and embedding of hard scale layers into the surface by rolls.",
    ],
    onleme: [
      "Etkin birincil tufal giderme",
      "Mold flux yönetimi (viskozite, besleme hızı)",
      "Refrakter kontrol ve değişim programı",
    ],
    onleme_en: [
      "Effective primary scale removal",
      "Mold flux management (viscosity, feeding rate)",
      "Refractory monitoring and replacement program",
    ],
    kaynak: "Sasaki Y. et al. — ISIJ Int. 2004; ASM Metals Handbook, Vol. 9",
  },
  {
    no: 22,
    slug: "kabuk-makro-inkluzyion-2",
    category: "flat",
    tr: "Kabuk, Makro İnklüzyon (Vaka 2)",
    en: "Sliver, Macro Inclusion — Case 2",
    tags: ["kabuk", "sliver", "inklüzyon", "MnS", "iç oksidasyon", "bobin"],
    images: [],
    imgLabels: [],
    imgLabels_en: [],
    sikayet: "Çizik, kabuk",
    sikayet_en: "Scratch, sliver",
    tespitler: [
      "Kusur yassı mamül hammadde yüzeyinde gözle ayırt edilebilmektedir.",
      "Düz çizgi şeklinde veya parçalı şekilde ele gelen bir ayrıntıdır.",
      "Mikro inceleme ile kök neden araştırması yapılmalı; sürekli döküm ve haddeleme parametreleri gözden geçirilmelidir.",
    ],
    tespitler_en: [
      "Defect is distinguishable to the eye on flat product feedstock surface.",
      "It appears as a detail in straight-line or broken sections.",
      "Root cause investigation through microscopy is necessary; continuous casting and rolling parameters should be reviewed.",
    ],
    nedenler: [
      "Kabuk kusurları, döküm sırasında yüzeyde oluşan mikroskopik çatlakların haddeleme sırasında açılmasıyla meydana gelir.",
      "Yüzey segregasyonu, MnS yönelmesi veya kalıntı inklüzyonların yüzeye çıkmasıyla ilişkilidir.",
    ],
    nedenler_en: [
      "Shell defects form when microscopic cracks on the surface during casting open during rolling.",
      "Associated with surface segregation, MnS orientation, or residual inclusions surfacing.",
    ],
    onleme: [
      "Slab yüzey muayenesi; kalıp içi sıcaklık ve soğutma kontrolü",
      "Merdane hizalanması ve yüzey düzgünlüğü kontrolü",
      "Etkin tufal temizliği",
    ],
    onleme_en: [
      "Slab surface inspection; mold temperature and cooling control",
      "Roll alignment and surface smoothness control",
      "Effective scale removal",
    ],
    kaynak: "Hasse D. — Surface Quality in Hot Rolling of Steel; ASM Handbook, Volume 14A",
  },
  {
    no: 23,
    slug: "cizik",
    category: "flat",
    tr: "Çizik",
    en: "Scratch",
    tags: ["çizik", "scratch", "merdane", "forklift", "depolama", "oksitlenme"],
    images: [],
    imgLabels: [],
    imgLabels_en: [],
    sikayet: "Yüzeyde çizik, bükme prosesinde yırtılma",
    sikayet_en: "Surface scratch, tearing in bending process",
    tespitler: [
      "Kusur yassı mamül yüzeyinde gözle görülebilmekte olup çizik bulunan bölgelerin bükme prosesine gelen yerlerde yırtılma şeklinde kendini gösterebilmektedir.",
      "Makro ve mikroskopik görüntülerde yüzeyde önceki proseslerde oluşmuş çizik kusuru ve zamana bağlı oksitlenme tespit edilebilmektedir.",
    ],
    tespitler_en: [
      "Defect is visible to the eye on flat product surface and can manifest as tearing in bending process at scratched regions.",
      "Scratch defects from previous processes and time-dependent oxidation are detected in macro and microscopic views.",
    ],
    nedenler: [
      "Üretim kaynaklı: Merdane yüzeyinde yabancı partikül (oksit, tufal, çapak).",
      "Üretim kaynaklı: Sarıcı ve yönlendirici makaraların yüzeyinde sert partikül veya yüzey aşınması.",
      "Korozyon kaynaklı: Bobinlerin elleçlenmesi sırasında mekanik temas (forklift çatalı, zincir, kanca).",
    ],
    nedenler_en: [
      "Production-related: Foreign particles on roll surface (oxide, scale, spall).",
      "Production-related: Hard particles on wrapper and guide roll surfaces or surface wear.",
      "Corrosion-related: Mechanical contact during coil handling (forklift tines, chains, hooks).",
    ],
    onleme: [
      "Haddeleme hattı temizliği ve doğru yağlama",
      "Merdane yüzey kontrolü",
      "Uygun lojistik ve depolama koşulları",
      "Çizik yönünün hadde yönüyle ilişkisi ve mikroyapıda oksidasyon varlığı değerlendirilmelidir",
    ],
    onleme_en: [
      "Rolling mill line cleaning and proper lubrication",
      "Roll surface inspection",
      "Appropriate logistics and storage conditions",
      "Evaluate scratch direction relative to rolling direction and presence of oxidation in microstructure",
    ],
    kaynak: "ASM Handbook, Volume 5: Surface Engineering",
  },
  {
    no: 24,
    slug: "rulo-kirigi",
    category: "flat",
    tr: "Rulo Kırığı",
    en: "Coil Break",
    tags: ["rulo kırığı", "coil break", "YPE", "C", "N", "sarılma sıcaklığı", "temper"],
    images: ["image77.JPG","image78.JPG"],
    imgLabels: ["Yüksek şiddetli rulo kırığı","Düşük şiddetli rulo kırığı"],
    imgLabels_en: ["High-severity coil break","Low-severity coil break"],
    sikayet: "Kusurlu yüzey, rulo kırığı, dalgalı yüzey",
    sikayet_en: "Defective surface, coil break, wavy surface",
    tespitler: [
      "Sıcak haddelenmiş düşük karbonlu çelik bobinlerin kesme hatlarında açılması sırasında bobin genişliği boyunca haddeleme yönüne dik olarak gelişen, düzensiz aralıklarla tekrarlayan enine kırılmalardır.",
      "Bobin açma ve germe sırasında malzemenin yüzeyinde metalik parlaklık gösteren hatlar halinde gözlemlenir.",
      "Mikro incelemelerde majör bir uygunsuzluk görülmeyebilir; mekanik özellikler ve yüzey görüntüsü ile birlikte değerlendirilmelidir.",
    ],
    tespitler_en: [
      "Transverse cracks developing at irregular intervals across coil width perpendicular to rolling direction that occur during opening at cutting lines of hot-rolled low-carbon steel coils.",
      "Observed as bright metallic lines on the material surface during coil opening and stretching.",
      "Major microstructural abnormality may not be visible in microscopy; should be evaluated together with mechanical properties and surface appearance.",
    ],
    nedenler: [
      "Sarılma sıcaklığı çok yüksekse serbest karbon artar → rulo kırığı; çok düşükse dalga kusuru oluşur.",
      "Yüksek YPE (Yield Point Elongation): C ve N atomlarının difüzyonu sonucu dislokasyon yoğunluğu artışı; N atomlarının katkısı özellikle belirgindir.",
      "Homojen olmayan tane boyutu rulo kırığına hassasiyeti artırır.",
    ],
    nedenler_en: [
      "If coiling temperature is too high, free carbon increases → coil break; if too low, wave defect occurs.",
      "High YPE (Yield Point Elongation): dislocation density increase from diffusion of C and N atoms; N atom contribution is particularly prominent.",
      "Non-uniform grain size increases susceptibility to coil break.",
    ],
    onleme: [
      "Sarılma sıcaklığının optimum aralıkta kontrolü",
      "Serbest C ve N miktarı azaltılmalı; N, Al ile bağlanmalıdır",
      "YPE değerinin azaltılması hedeflenmelidir",
      "Küçük ve homojen tane boyutu sağlanmalıdır",
      "Temper haddeleme kullanımı (Push-Pull hattı gibi hatlarda)",
    ],
    onleme_en: [
      "Control coiling temperature within optimal range",
      "Reduce free C and N; bind N with Al",
      "Target reduction of YPE value",
      "Ensure small and homogeneous grain size",
      "Use temper rolling (on lines like Push-Pull mill)",
    ],
    kaynak: "ASM Handbook, Volume 5: Surface Engineering",
  },
  {
    no: 25,
    slug: "kizil-oksit",
    category: "flat",
    tr: "Kızıl Oksit",
    en: "Red Scale",
    tags: ["kızıl oksit", "red scale", "fayalit", "Fe₂SiO₄", "Si", "1173°C", "ISIJ"],
    images: [],
    imgLabels: [],
    imgLabels_en: [],
    sikayet: "Kusurlu yüzey, tufal, kaplama problemi",
    sikayet_en: "Defective surface, scale, coating problem",
    tespitler: [
      "Kızıl oksit, sıcak haddeleme sırasında yüksek sıcaklık ve kimyasal bileşime bağlı olarak çelik yüzeyinde oluşan oksit tabakasıdır.",
      "Genellikle kırmızımsı, kahverengi veya gri-siyah renkte görülebilir. Özellikle yüksek Si içeren çeliklerde belirgindir.",
      "Kalın ve yapışkan tufal tabakaları haddeleme sonrası yüzeyden kolay ayrılamaz ve yüzey kalitesini olumsuz etkiler.",
    ],
    tespitler_en: [
      "Red scale is an oxide layer formed on steel surface during hot rolling depending on high temperature and chemical composition.",
      "Typically appears reddish, brown, or gray-black in color. Particularly prominent in high-Si steels.",
      "Thick and adhesive scale layers do not easily separate from the surface after rolling and negatively impact surface quality.",
    ],
    nedenler: [
      "Yüksek Si ve Nb içeren çeliklerde kızıl oksit eğilimi artar.",
      "Fayalit (Fe₂SiO₄) oluşumu: FeO (wüstit) ile SiO₂ reaksiyonu → fayalit erime sıcaklığı 1173 °C üzerinde yapışkan sıvı faz → yüzeye kuvvetle bağlanır.",
      "900 °C altında tufal kırılgan hale gelir → kızıl oksit riski artar.",
    ],
    nedenler_en: [
      "Red scale tendency increases in high-Si and Nb steels.",
      "Fayalite (Fe₂SiO₄) formation: reaction of FeO (wüstite) with SiO₂ → above fayalite melting temperature 1173 °C, sticky liquid phase forms and strongly adheres to surface.",
      "Below 900 °C, scale becomes brittle → red scale risk increases.",
    ],
    onleme: [
      "Kimyasal kompozisyon kontrolü: Si ve Nb içeriği minimize edilmeli",
      "Slab ısıtma fırını sıcaklığı fayalit erime sıcaklığı olan 1173 °C altında tutulursa yapışma azalır",
      "Haddeleme adımları arasında sürekli descaling uygulanmalı",
      "Uzun süreli tavlama ve kalın tufal oluşumu önlenmeli",
    ],
    onleme_en: [
      "Control chemical composition: minimize Si and Nb content",
      "Maintain slab heating furnace temperature below fayalite melting temperature of 1173 °C to reduce adhesion",
      "Continuous descaling between rolling steps",
      "Prevent prolonged annealing and thick scale formation",
    ],
    kaynak: "ASM Handbook, Volume 1; ASM Handbook, Volume 4A; Sasaki Y. et al. — ISIJ International 2004",
  },
];

// Convenience: map slug → case
export const CASE_BY_SLUG = Object.fromEntries(CASES.map(c => [c.slug, c]));
// Map: category → cases
export const CASES_BY_CATEGORY = {
  wire: CASES.filter(c => c.category === "wire"),
  flat: CASES.filter(c => c.category === "flat"),
};
